server:
  port: 8080

---
spring:
  profile:
    active: local-dev
    
---
spring:
  profile: local-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/Blogs
    username : postgres
    password :  1234
  jpa:
    properties:
      hibernate:
       format_sql: true
    show-sql: true
    hibernate.ddl-auto : update
      
